apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-4
spec:
  storageClassName: ebs-sc
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0723f0f3b6e16bac3
    fsType: xfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-west-2a
